(package "nerd-icons"
         "0.1.0"
         "Emacs Nerd Font Icons Library")

(website-url "https://github.com/rainstormstudio/nerd-icons.el")
(keywords "lisp")

(package-file "nerd-icons.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
